### ISSUE TITLE
something wrong with Streamlit

### ISSUE THREAD

**Issue by Presiton** [davidefiocco/streamlit-fastapi-model-serving#21]
I use ubuntu virtual machine 18.04 to deploy your program.

**Comment by Presiton** [comment]
I use following steps to finish this.
1. sudo apt install docker.io
2. sudo apt install docker-compose
3. systemctl start docker
4. git clone the project code and enter the directory
5. sudo docker-compose build
6. sudo docker-compose up

then the streamlit page always display "Please Wait", when I refresh the page, the terminal logs a problem I search for a long time but I can not resolve. Thanks for your work and waiting for your reply. 

streamlit    | Exception in thread ScriptRunner.scriptThread:
streamlit    | Traceback (most recent call last):
streamlit    |   File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
streamlit    |     self.run()
streamlit    |   File "/usr/local/lib/python3.7/threading.py", line 870, in run
streamlit    |     self._target(*self._args, **self._kwargs)
streamlit    |   File "/usr/local/lib/python3.7/site-packages/streamlit/script_runner.py", line 172, in _process_request_queue
streamlit    |     self._run_script(data)
streamlit    |   File "/usr/local/lib/python3.7/site-packages/streamlit/script_runner.py", line 272, in _run_script
streamlit    |     self.on_event.send(ScriptRunnerEvent.SCRIPT_STARTED)
streamlit    |   File "/usr/local/lib/python3.7/site-packages/blinker/base.py", line 267, in send
streamlit    |     for receiver in self.receivers_for(sender)]
streamlit    |   File "/usr/local/lib/python3.7/site-packages/blinker/base.py", line 267, in <listcomp>
streamlit    |     for receiver in self.receivers_for(sender)]
streamlit    |   File "/usr/local/lib/python3.7/site-packages/streamlit/report_session.py", line 285, in _on_scriptrunner_event
streamlit    |     self._enqueue_new_report_message()
streamlit    |   File "/usr/local/lib/python3.7/site-packages/streamlit/report_session.py", line 383, in _enqueue_new_report_message
streamlit    |     _populate_user_info_msg(imsg.user_info)
streamlit    |   File "/usr/local/lib/python3.7/site-packages/streamlit/report_session.py", line 706, in _populate_user_info_msg
streamlit    |     msg.installation_id = Installation.instance().installation_id
streamlit    |   File "/usr/local/lib/python3.7/site-packages/streamlit/metrics_util.py", line 129, in instance
streamlit    |     cls._instance = Installation()
streamlit    |   File "/usr/local/lib/python3.7/site-packages/streamlit/metrics_util.py", line 133, in __init__
streamlit    |     self.installation_id_v1 = str(uuid.uuid5(uuid.NAMESPACE_DNS, _get_machine_id()))
streamlit    |   File "/usr/local/lib/python3.7/site-packages/streamlit/metrics_util.py", line 49, in _get_machine_id
streamlit    |     subprocess.run(["sudo", "dbus-uuidgen", "--ensure"])
streamlit    |   File "/usr/local/lib/python3.7/subprocess.py", line 488, in run
streamlit    |     with Popen(*popenargs, **kwargs) as process:
streamlit    |   File "/usr/local/lib/python3.7/subprocess.py", line 800, in __init__
streamlit    |     restore_signals, start_new_session)
streamlit    |   File "/usr/local/lib/python3.7/subprocess.py", line 1551, in _execute_child
streamlit    |     raise child_exception_type(errno_num, err_msg, err_filename)
streamlit    | FileNotFoundError: [Errno 2] No such file or directory: 'sudo': 'sudo'
streamlit    | 
streamlit    | Exception in thread ScriptRunner.scriptThread:
streamlit    | Traceback (most recent call last):
streamlit    |   File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
streamlit    |     self.run()
streamlit    |   File "/usr/local/lib/python3.7/threading.py", line 870, in run
streamlit    |     self._target(*self._args, **self._kwargs)
streamlit    |   File "/usr/local/lib/python3.7/site-packages/streamlit/script_runner.py", line 172, in _process_request_queue
streamlit    |     self._run_script(data)
streamlit    |   File "/usr/local/lib/python3.7/site-packages/streamlit/script_runner.py", line 272, in _run_script
streamlit    |     self.on_event.send(ScriptRunnerEvent.SCRIPT_STARTED)
streamlit    |   File "/usr/local/lib/python3.7/site-packages/blinker/base.py", line 267, in send
streamlit    |     for receiver in self.receivers_for(sender)]
streamlit    |   File "/usr/local/lib/python3.7/site-packages/blinker/base.py", line 267, in <listcomp>
streamlit    |     for receiver in self.receivers_for(sender)]
streamlit    |   File "/usr/local/lib/python3.7/site-packages/streamlit/report_session.py", line 285, in _on_scriptrunner_event
streamlit    |     self._enqueue_new_report_message()
streamlit    |   File "/usr/local/lib/python3.7/site-packages/streamlit/report_session.py", line 383, in _enqueue_new_report_message
streamlit    |     _populate_user_info_msg(imsg.user_info)
streamlit    |   File "/usr/local/lib/python3.7/site-packages/streamlit/report_session.py", line 706, in _populate_user_info_msg
streamlit    |     msg.installation_id = Installation.instance().installation_id
streamlit    |   File "/usr/local/lib/python3.7/site-packages/streamlit/metrics_util.py", line 129, in instance
streamlit    |     cls._instance = Installation()
streamlit    |   File "/usr/local/lib/python3.7/site-packages/streamlit/metrics_util.py", line 133, in __init__
streamlit    |     self.installation_id_v1 = str(uuid.uuid5(uuid.NAMESPACE_DNS, _get_machine_id()))
streamlit    |   File "/usr/local/lib/python3.7/site-packages/streamlit/metrics_util.py", line 49, in _get_machine_id
streamlit    |     subprocess.run(["sudo", "dbus-uuidgen", "--ensure"])
streamlit    |   File "/usr/local/lib/python3.7/subprocess.py", line 488, in run
streamlit    |     with Popen(*popenargs, **kwargs) as process:
streamlit    |   File "/usr/local/lib/python3.7/subprocess.py", line 800, in __init__
streamlit    |     restore_signals, start_new_session)
streamlit    |   File "/usr/local/lib/python3.7/subprocess.py", line 1551, in _execute_child
streamlit    |     raise child_exception_type(errno_num, err_msg, err_filename)
streamlit    | FileNotFoundError: [Errno 2] No such file or directory: 'sudo': 'sudo'
streamlit    | 
streamlit    | Exception in thread ScriptRunner.scriptThread:
streamlit    | Traceback (most recent call last):
streamlit    |   File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
streamlit    |     self.run()
streamlit    |   File "/usr/local/lib/python3.7/threading.py", line 870, in run
streamlit    |     self._target(*self._args, **self._kwargs)
streamlit    |   File "/usr/local/lib/python3.7/site-packages/streamlit/script_runner.py", line 172, in _process_request_queue
streamlit    |     self._run_script(data)
streamlit    |   File "/usr/local/lib/python3.7/site-packages/streamlit/script_runner.py", line 272, in _run_script
streamlit    |     self.on_event.send(ScriptRunnerEvent.SCRIPT_STARTED)
streamlit    |   File "/usr/local/lib/python3.7/site-packages/blinker/base.py", line 267, in send
streamlit    |     for receiver in self.receivers_for(sender)]
streamlit    |   File "/usr/local/lib/python3.7/site-packages/blinker/base.py", line 267, in <listcomp>
streamlit    |     for receiver in self.receivers_for(sender)]
streamlit    |   File "/usr/local/lib/python3.7/site-packages/streamlit/report_session.py", line 285, in _on_scriptrunner_event
streamlit    |     self._enqueue_new_report_message()
streamlit    |   File "/usr/local/lib/python3.7/site-packages/streamlit/report_session.py", line 383, in _enqueue_new_report_message
streamlit    |     _populate_user_info_msg(imsg.user_info)
streamlit    |   File "/usr/local/lib/python3.7/site-packages/streamlit/report_session.py", line 706, in _populate_user_info_msg
streamlit    |     msg.installation_id = Installation.instance().installation_id
streamlit    |   File "/usr/local/lib/python3.7/site-packages/streamlit/metrics_util.py", line 129, in instance
streamlit    |     cls._instance = Installation()
streamlit    |   File "/usr/local/lib/python3.7/site-packages/streamlit/metrics_util.py", line 133, in __init__
streamlit    |     self.installation_id_v1 = str(uuid.uuid5(uuid.NAMESPACE_DNS, _get_machine_id()))
streamlit    |   File "/usr/local/lib/python3.7/site-packages/streamlit/metrics_util.py", line 49, in _get_machine_id
streamlit    |     subprocess.run(["sudo", "dbus-uuidgen", "--ensure"])
streamlit    |   File "/usr/local/lib/python3.7/subprocess.py", line 488, in run
streamlit    |     with Popen(*popenargs, **kwargs) as process:
streamlit    |   File "/usr/local/lib/python3.7/subprocess.py", line 800, in __init__
streamlit    |     restore_signals, start_new_session)
streamlit    |   File "/usr/local/lib/python3.7/subprocess.py", line 1551, in _execute_child
streamlit    |     raise child_exception_type(errno_num, err_msg, err_filename)
streamlit    | FileNotFoundError: [Errno 2] No such file or directory: 'sudo': 'sudo'
streamlit    | 
streamlit    | Exception in thread ScriptRunner.scriptThread:
streamlit    | Traceback (most recent call last):
streamlit    |   File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
streamlit    |     self.run()
streamlit    |   File "/usr/local/lib/python3.7/threading.py", line 870, in run
streamlit    |     self._target(*self._args, **self._kwargs)
streamlit    |   File "/usr/local/lib/python3.7/site-packages/streamlit/script_runner.py", line 172, in _process_request_queue
streamlit    |     self._run_script(data)
streamlit    |   File "/usr/local/lib/python3.7/site-packages/streamlit/script_runner.py", line 272, in _run_script
streamlit    |     self.on_event.send(ScriptRunnerEvent.SCRIPT_STARTED)
streamlit    |   File "/usr/local/lib/python3.7/site-packages/blinker/base.py", line 267, in send
streamlit    |     for receiver in self.receivers_for(sender)]
streamlit    |   File "/usr/local/lib/python3.7/site-packages/blinker/base.py", line 267, in <listcomp>
streamlit    |     for receiver in self.receivers_for(sender)]
streamlit    |   File "/usr/local/lib/python3.7/site-packages/streamlit/report_session.py", line 285, in _on_scriptrunner_event
streamlit    |     self._enqueue_new_report_message()
streamlit    |   File "/usr/local/lib/python3.7/site-packages/streamlit/report_session.py", line 383, in _enqueue_new_report_message
streamlit    |     _populate_user_info_msg(imsg.user_info)
streamlit    |   File "/usr/local/lib/python3.7/site-packages/streamlit/report_session.py", line 706, in _populate_user_info_msg
streamlit    |     msg.installation_id = Installation.instance().installation_id
streamlit    |   File "/usr/local/lib/python3.7/site-packages/streamlit/metrics_util.py", line 129, in instance
streamlit    |     cls._instance = Installation()
streamlit    |   File "/usr/local/lib/python3.7/site-packages/streamlit/metrics_util.py", line 133, in __init__
streamlit    |     self.installation_id_v1 = str(uuid.uuid5(uuid.NAMESPACE_DNS, _get_machine_id()))
streamlit    |   File "/usr/local/lib/python3.7/site-packages/streamlit/metrics_util.py", line 49, in _get_machine_id
streamlit    |     subprocess.run(["sudo", "dbus-uuidgen", "--ensure"])
streamlit    |   File "/usr/local/lib/python3.7/subprocess.py", line 488, in run
streamlit    |     with Popen(*popenargs, **kwargs) as process:
streamlit    |   File "/usr/local/lib/python3.7/subprocess.py", line 800, in __init__
streamlit    |     restore_signals, start_new_session)
streamlit    |   File "/usr/local/lib/python3.7/subprocess.py", line 1551, in _execute_child
streamlit    |     raise child_exception_type(errno_num, err_msg, err_filename)
streamlit    | FileNotFoundError: [Errno 2] No such file or directory: 'sudo': 'sudo'

**Comment by Presiton** [comment]
![image](https://user-images.githubusercontent.com/37797314/167300679-91ea7824-8d8b-4b61-910d-fb4fe7b66fc5.png)

**Comment by Presiton** [comment]
![image](https://user-images.githubusercontent.com/37797314/167300873-b43a0c34-cf7f-4d2b-9741-0d479d658ac2.png)

**Comment by davidefiocco** [comment]
Hi there, 

thanks for reporting this! It seems that we're hit by this issue https://stackoverflow.com/questions/61871050/filenotfounderror-errno-2-no-such-file-or-directory-sudo-sudo
but by using a newer version of streamlit the problem seems solved. Let me know if the new version on master fixes this for you so that we can close this!
