### ISSUE TITLE
"FileNotFoundError: [Errno 2] No such file or directory: 'sudo': 'sudo'" on Docker build

### ISSUE THREAD

**Issue by quoidautre** [davidefiocco/streamlit-fastapi-model-serving#34]
Hi,

I try to test yout repo, but there's an error on the docker build : 

```
Creating fastapi ... done
Creating streamlit ... done
Attaching to fastapi, streamlit
streamlit    | Generate machine-id
streamlit    | Traceback (most recent call last):
streamlit    |   File "/usr/local/bin/streamlit", line 5, in <module>
streamlit    |     from streamlit.cli import main
streamlit    |   File "/usr/local/lib/python3.7/site-packages/streamlit/__init__.py", line 74, in <module>
streamlit    |     subprocess.run(["sudo", "dbus-uuidgen", "--ensure"])
streamlit    |   File "/usr/local/lib/python3.7/subprocess.py", line 488, in run
streamlit    |     with Popen(*popenargs, **kwargs) as process:
streamlit    |   File "/usr/local/lib/python3.7/subprocess.py", line 800, in __init__
streamlit    |     restore_signals, start_new_session)
streamlit    |   File "/usr/local/lib/python3.7/subprocess.py", line 1567, in _execute_child
streamlit    |     raise child_exception_type(errno_num, err_msg, err_filename)
streamlit    | FileNotFoundError: [Errno 2] No such file or directory: 'sudo': 'sudo'

```

have you an idea please ?
Thanks

F.

**Comment by davidefiocco** [comment]
Hello! Thanks for trying the code out. Can you `git pull` the repo with the current, updated Docker images and package versions? Hopefully this should solve the problem.

**Comment by quoidautre** [comment]
Hi,
Thanks to your answer :).

It's better after a pull, but for now, I've not the same menus, options and other in vscode. 
So, I can't really debugging the project. The python interpreter don't show me the python in container, only local. But I'm in...

F.
